[[linter]]
code = 'CLANGFORMAT'
include_patterns = [
    'libkineto/**/*.cpp',
    'libkineto/**/*.h',
    'libkineto/**/*.cc',
    'libkineto/**/*.hpp',
]
exclude_patterns = [
    'libkineto/third_party/**',
    'libkineto/build/**',
]
command = [
    'python3',
    'tools/linter/adapters/clangformat_linter.py',
    '--binary=clang-format',
    '@{{PATHSFILE}}'
]
is_formatter = true

[[linter]]
code = 'NEWLINE'
include_patterns = [
    'libkineto/**/*.cpp',
    'libkineto/**/*.h',
    'libkineto/**/*.cc',
    'libkineto/**/*.hpp',
    'libkineto/**/*.cmake',
    'libkineto/**/CMakeLists.txt',
]
exclude_patterns = [
    'libkineto/third_party/**',
]
command = [
    'python3',
    'tools/linter/adapters/newlines_linter.py',
    '@{{PATHSFILE}}',
]
is_formatter = true

[[linter]]
code = 'SPACES'
include_patterns = [
    'libkineto/**/*.cpp',
    'libkineto/**/*.h',
    'libkineto/**/*.cc',
    'libkineto/**/*.hpp',
]
exclude_patterns = [
    'libkineto/third_party/**',
]
command = [
    'python3',
    'tools/linter/adapters/grep_linter.py',
    '--pattern=[[:blank:]]$',
    '--linter-name=SPACES',
    '--error-name=trailing spaces',
    """--error-description=\
        This line has trailing spaces.  Please remove them.\
    """,
    '@{{PATHSFILE}}'
]

[[linter]]
code = 'TABS'
include_patterns = [
    'libkineto/**/*.cpp',
    'libkineto/**/*.h',
    'libkineto/**/*.cc',
    'libkineto/**/*.hpp',
]
exclude_patterns = [
    'libkineto/third_party/**',
]
command = [
    'python3',
    'tools/linter/adapters/grep_linter.py',
    '--pattern=\t',
    '--linter-name=TABS',
    '--error-name=saw a tab',
    """--error-description=\
        This line has a tab character.  Please convert it to spaces.\
    """,
    '@{{PATHSFILE}}'
]
